apiVersion: v1
kind: Namespace
metadata:
    name: create-namespace-pod-sidecar
    labels:
        istio-injection: "enabled"
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: create-namespace-pod-sidecar
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']

